### ISSUE TITLE
PBJ failed to parse a record file

### ISSUE THREAD

**Issue by jasperpotts** [hashgraph/pbj#45]
### Description

When trying to parse a record file from Hedera main-net in V6 record format defined in https://hips.hedera.com/hip/hip-435. The first 4 bytes are a version `int` followed by protobuf object `RecordStreamFile`. PBJ failed with exception:
```
Exception in thread "main" java.nio.BufferUnderflowException
	at com.hedera.pbj.runtime.io.stream.ReadableStreamingData.readByte(ReadableStreamingData.java:111)
	at com.hedera.pbj.runtime.io.ReadableSequentialData.readVarLong(ReadableSequentialData.java:449)
	at com.hedera.pbj.runtime.io.ReadableSequentialData.readVarInt(ReadableSequentialData.java:433)
	at com.hedera.hapi.streams.codec.RecordStreamFileProtoCodec.parseInternal(RecordStreamFileProtoCodec.java:170)
	at com.hedera.hapi.streams.codec.RecordStreamFileProtoCodec.parse(RecordStreamFileProtoCodec.java:41)
	at com.hedera.hapi.streams.codec.RecordStreamFileProtoCodec.parse(RecordStreamFileProtoCodec.java:26)
	at com.hedera.node.app.records.RecordStreamTest.generateRecordStreamItems3(RecordStreamTest.java:151)
	at com.hedera.node.app.records.RecordStreamTest.main(RecordStreamTest.java:119)
```

### Steps to reproduce

Parsing with PBJ throws exception
```
    private static void fails() throws Exception {
        final URL recordFileUrl = RecordStreamTest.class.getResource("/record-files/2023-05-01T00_00_00.026034002Z.rcd.gz");
        try (final ReadableStreamingData in = new ReadableStreamingData(
                new GZIPInputStream(Files.newInputStream(Path.of(recordFileUrl.toURI()))))) {
            int version = in.readInt();
            System.out.println("version = " + version);
            RecordStreamFile recordStreamFile =  RecordStreamFile.PROTOBUF.parse(in);
            System.out.println("recordStreamFile = " + recordStreamFile);
        }
    }
```
Parsing with Google protocol generated parser works fine
```
    private static void works() throws Exception {
        final URL recordFileUrl = RecordStreamTest.class.getResource("/record-files/2023-05-01T00_00_00.026034002Z.rcd.gz");
        try (final DataInputStream in = new DataInputStream(
                new GZIPInputStream(Files.newInputStream(Path.of(recordFileUrl.toURI()))))) {
            int version = in.readInt();
            System.out.println("version = " + version);
            com.hedera.services.stream.proto.RecordStreamFile recordStreamFile =
                    com.hedera.services.stream.proto.RecordStreamFile.parseFrom(in);
            System.out.println("recordStreamFile = " + recordStreamFile);
        }
    }
```

**Comment by jasperpotts** [comment]
[2023-05-01T00_00_00.026034002Z.rcd.gz](https://github.com/hashgraph/pbj/files/11502975/2023-05-01T00_00_00.026034002Z.rcd.gz)
failing file

**Comment by jasperpotts** [comment]
I found the issue, we are using ReadableStreamingData in `while (input.hasRemaining()) {...}`  loop in `com/hedera/hapi/streams/codec/RecordStreamFileProtoCodec.java:167`. It can not detect the end of file EOF because `hasRemaining()` is always true. We used to do one byte of read-ahead to make this work. @rbair23 removed that and I am not sure the new answer.

**Comment by jasperpotts** [comment]
workaround

**Comment by LLITCHEV** [comment]
Fixed with https://github.com/hashgraph/pbj/pull/47
